### PR TITLE
PCM-3133: Added getUserBySSO API from strata.js

### PR DESCRIPTION
**Pull request by jtrantin**
@vrathee @gandhikeyur Please review.

### CODE REVIEW

**Comment by jtrantin** [comment]
Related to https://github.com/redhataccess/stratajs/pull/37

**Comment by gandhikeyur** [comment]
Reviewed

**Comment by renujhamtani** [comment]
looks good!

**Comment by gandhikeyur** [comment]
1.2.17 Tagged and Published

**Pull request merged**
