### PR TITLE
PCM-3090: Adding user-role update API

### PR DESCRIPTION
**Pull request by jtrantin**
@vrathee @gandhikeyur Please review.

https://projects.engineering.redhat.com/browse/PCM-3090

### CODE REVIEW

**Comment by jtrantin** [comment]
Just realized I will need some more changes, don't review and merge, I will update this PR..

**Comment by jtrantin** [comment]
@vrathee @gandhikeyur This is ready for review.

**Comment by gandhikeyur** [comment]
Reviewed

**Comment by renujhamtani** [comment]
Reviewed!

**Pull request merged**
